### ISSUE TITLE
Front-end para Projeto Free

### ISSUE THREAD

**Issue by vps-victor** [DevsFreeOrg/.github#2]
# Requisitos:

_Todos os requisitos abaixo precisam ser implementados_

- HTML
- CSS
- JavaScript
- Manipular Elementos DOM
- React
  - Conhecimento sólido em componentes usando bibliotecas de terceiros (Tailwind).
  - Estilização 
- Next.js
  - API 
  - Rotas
- TypeScript.
- Hooks

# Desafio:

1. Crie um projeto Next.js com TypeScript que utilize a API pública do GitHub para buscar e exibir uma lista de repositórios de usuários específicos. A página inicial do aplicativo deve permitir que o usuário insira o nome de usuário do GitHub que deseja pesquisar.
2. A página inicial do aplicativo deve exibir uma lista dos repositórios desse usuário, com informações básicas, como nome do repositório, descrição e número de estrelas.
3. Adicione um botão "ver detalhes" a cada item da lista de repositórios. Quando o botão é clicado, o usuário deve ser levado a uma página de detalhes que exibe informações mais detalhadas sobre o repositório selecionado, como o número de estrelas, forks e as issues abertas.
4. Estilize o aplicativo usando CSS Modules ou uma biblioteca de estilização de sua escolha.

**Comment by kalebejobs** [comment]
Outro nível aqui.

**Comment by DanielKitanaxiFilipe** [comment]
Vou desenvolver ja ja
